#!/usr/bin/env bash
#Install and configure HAproxy to send traffic to web-01 and web-02
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install haproxy -y
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo echo "frontend  prideland_alx_frontend
        bind *:80
        stats uri /haproxy?stats
        default_backend prideland_alx_backend
backend prideland_alx_backend
        balance roundrobin
        server 45650-web-01 54.144.44.80:80 check
        server 45650-web-02 100.25.191.46:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
